apiVersion: v1
kind: Service
metadata:
  name: crm-api-service
spec:
  selector:
    app: crm-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: crm-frontend-service
spec:
  selector:
    app: crm-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
